<?php

use yii\db\Migration;

/**
 * Class m220131_031848_insert_produk
 */
class m220131_031848_insert_produk extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        // NEW INSERT DATA PRODUK
        $tableProduk = '{{%produk}}';

        // PULSA TELKOMSEL
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TN5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TN10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM40',
            'nama_produk'  => '40K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '1',
            'kode_produk'  => 'TM500',
            'nama_produk'  => '500K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // DATA TELKOMSEL
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDH25',
            'nama_produk'  => '25GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'MAXGH3',
            'nama_produk'  => '2GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'MAXGH15',
            'nama_produk'  => '15GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFP5',
            'nama_produk'  => '5GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFP12',
            'nama_produk'  => '12GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFP8',
            'nama_produk'  => '8GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFH5',
            'nama_produk'  => '5GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFH8',
            'nama_produk'  => '8GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFH3',
            'nama_produk'  => '3GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '1',
            'kode_produk'  => 'TDFH12',
            'nama_produk'  => '12GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // PULSA XL
        $this->insert($tableProduk, array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 2,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH300',
            'nama_produk'  => '300K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH500',
            'nama_produk'  => '500K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '3',
            'kode_produk'  => 'XH1000',
            'nama_produk'  => '1000K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // DATA XL
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XLCH3',
            'nama_produk'  => '6GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XLCH4',
            'nama_produk'  => '18GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XLDH3',
            'nama_produk'  => '3GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XLDH5',
            'nama_produk'  => '6GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XLDH7',
            'nama_produk'  => '12GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 2,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XDCP5',
            'nama_produk'  => '5GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XDCP15',
            'nama_produk'  => '15GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '3',
            'kode_produk'  => 'XDCP20',
            'nama_produk'  => '20GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // PULSA AXIS
        $this->insert($tableProduk, array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH300',
            'nama_produk'  => '300K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH500',
            'nama_produk'  => '500K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '4',
            'kode_produk'  => 'XH1000',
            'nama_produk'  => '1000K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // DATA AXIS
        $this->insert($tableProduk, array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDB4',
            'nama_produk'  => '3GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDB8',
            'nama_produk'  => '8GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDB12',
            'nama_produk'  => '12GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDH2',
            'nama_produk'  => '2GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDH3',
            'nama_produk'  => '3GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDH5',
            'nama_produk'  => '8GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'AXDH7',
            'nama_produk'  => '12GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'ADM7',
            'nama_produk'  => '3GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '4',
            'kode_produk'  => 'ADM8',
            'nama_produk'  => '5GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // PULSA INDOSAT
        $this->insert($tableProduk, array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH40',
            'nama_produk'  => '40K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '2',
            'kode_produk'  => 'IH500',
            'nama_produk'  => '500K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // DATA INDOSAT
        $this->insert($tableProduk, array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDYP7',
            'nama_produk'  => '1GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUH1',
            'nama_produk'  => '1GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUH2',
            'nama_produk'  => '2GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUH7',
            'nama_produk'  => '7GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUH15',
            'nama_produk'  => '15GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUH100',
            'nama_produk'  => '60GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUF1',
            'nama_produk'  => '2GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUF3',
            'nama_produk'  => '8GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUF4',
            'nama_produk'  => '10GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUF6',
            'nama_produk'  => '25GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDUF7',
            'nama_produk'  => '50GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDVH2',
            'nama_produk'  => '2GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDVH7',
            'nama_produk'  => '7GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDVH15',
            'nama_produk'  => '15GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '2',
            'kode_produk'  => 'IDVH100',
            'nama_produk'  => 'Unlimited',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // PULSA THREE
        $this->insert($tableProduk, array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH40',
            'nama_produk'  => '40K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '6',
            'kode_produk'  => 'TH200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // DATA THREE
        $this->insert($tableProduk, array(
            'layanan_id'   => 2,
            'sub_produk'   => '6',
            'kode_produk'  => 'TRHM5',
            'nama_produk'  => '9GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '6',
            'kode_produk'  => 'TRDF33',
            'nama_produk'  => '33GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '6',
            'kode_produk'  => 'TDL1000',
            'nama_produk'  => '1GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '6',
            'kode_produk'  => 'TDL2000',
            'nama_produk'  => '2GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '6',
            'kode_produk'  => 'TDL5000',
            'nama_produk'  => '5GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '6',
            'kode_produk'  => 'TDL10000',
            'nama_produk'  => '10GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // PULSA SMARTFREN
        $this->insert($tableProduk, array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMH200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // DATA SMARTFREN
        $this->insert($tableProduk, array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMDP60',
            'nama_produk'  => '8GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMDP150',
            'nama_produk'  => '22GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMDP100',
            'nama_produk'  => '15GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SMDP200',
            'nama_produk'  => '30GB',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SNA30',
            'nama_produk'  => '6GB UNLIMITED',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SNA45',
            'nama_produk'  => '10GB UNLIMITED',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SNA65',
            'nama_produk'  => '18GB UNLIMITED',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 2,
            'sub_produk'   => '5',
            'kode_produk'  => 'SNA100',
            'nama_produk'  => '30GB UNLIMITED',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // PULSA BYU
        $this->insert($tableProduk, array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY5',
            'nama_produk'  => '5K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY10',
            'nama_produk'  => '10K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY25',
            'nama_produk'  => '25K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY40',
            'nama_produk'  => '40K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY50',
            'nama_produk'  => '50K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY100',
            'nama_produk'  => '100K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY150',
            'nama_produk'  => '150K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        $this->insert($tableProduk,array(
            'layanan_id'   => 1,
            'sub_produk'   => '7',
            'kode_produk'  => 'BYY200',
            'nama_produk'  => '200K',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // TAGIHAN LISTRIK
        // CEK
        $this->insert($tableProduk,array(
            'layanan_id'   => 3,
            'sub_produk'   => '0',
            'kode_produk'  => 'INQ3511',
            'nama_produk'  => 'Cek Tagihan Listrik',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '1',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        // BAYAR
        $this->insert($tableProduk,array(
            'layanan_id'   => 3,
            'sub_produk'   => '0',
            'kode_produk'  => 'PAY3511',
            'nama_produk'  => 'Bayar Tagihan Listrik',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));

        // TAGIHAN INDIHOME
        // CEK
        $this->insert($tableProduk,array(
            'layanan_id'   => 5,
            'sub_produk'   => '0',
            'kode_produk'  => 'INQ720',
            'nama_produk'  => 'Cek Tagihan Indihome',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '1',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
        // BAYAR
        $this->insert($tableProduk,array(
            'layanan_id'   => 5,
            'sub_produk'   => '0',
            'kode_produk'  => 'PAY720',
            'nama_produk'  => 'Bayar Tagihan Indihome',
            'harga_markup' => '0',
            'is_delete'    => '1',
            'jenis'        => '2',
            'created_by'   => 1,
            'created_at'   => time(),
            'updated_at'   => time(),
        ));
    }
}
